### ISSUE TITLE
[BUG] Error when Deploying Alternate Contacts Solution via CfCT

### ISSUE THREAD

**Issue by AdamDivall** [aws-samples/aws-security-reference-architecture-examples#108]
Hi There,

I'm running into an issue when trying to deploy the Alternate Contacts Solution through Customisations for Control Tower that is part of the SRA Repo.

The CodeBuild logs (Custom-Control-Tower-StackSet-CodeBuild) show the following:
```
{"time_stamp": "2022-08-04 11:08:40,441","log_level": "ERROR","log_message": Unhandled Exception: argument of type 'int' is not iterable}
Traceback (most recent call last):
  File "/codebuild/output/src245367560/src/state_machine_trigger.py", line 69, in main
    sm_input_list = get_stack_set_inputs()
  File "/codebuild/output/src245367560/src/state_machine_trigger.py", line 95, in get_stack_set_inputs
    return parse.stack_set_manifest()
  File "/codebuild/output/src245367560/src/cfct/manifest/manifest_parser.py", line 62, in stack_set_manifest
    return get_stack_set_input.parse_stack_set_manifest_v2()
  File "/codebuild/output/src245367560/src/cfct/manifest/manifest_parser.py", line 256, in parse_stack_set_manifest_v2
    sm_input = build.stack_set_state_machine_input_v2(
  File "/codebuild/output/src245367560/src/cfct/manifest/manifest_parser.py", line 370, in stack_set_state_machine_input_v2
    sm_params = self.param_handler.update_params(parameters, account_list,
  File "/codebuild/output/src245367560/src/cfct/manifest/cfn_params_handler.py", line 229, in update_params
    value = value if separator not in value else \
TypeError: argument of type 'int' is not iterable
Traceback (most recent call last):
  File "/codebuild/output/src245367560/src/state_machine_trigger.py", line 132, in <module>
    main()
  File "/codebuild/output/src245367560/src/state_machine_trigger.py", line 69, in main
    sm_input_list = get_stack_set_inputs()
  File "/codebuild/output/src245367560/src/state_machine_trigger.py", line 95, in get_stack_set_inputs
    return parse.stack_set_manifest()
  File "/codebuild/output/src245367560/src/cfct/manifest/manifest_parser.py", line 62, in stack_set_manifest
    return get_stack_set_input.parse_stack_set_manifest_v2()
  File "/codebuild/output/src245367560/src/cfct/manifest/manifest_parser.py", line 256, in parse_stack_set_manifest_v2
    sm_input = build.stack_set_state_machine_input_v2(
  File "/codebuild/output/src245367560/src/cfct/manifest/manifest_parser.py", line 370, in stack_set_state_machine_input_v2
    sm_params = self.param_handler.update_params(parameters, account_list,
  File "/codebuild/output/src245367560/src/cfct/manifest/cfn_params_handler.py", line 229, in update_params
    value = value if separator not in value else \
TypeError: argument of type 'int' is not iterable
```

My manifest.yaml entry is as below:
```
  # -----------------------------------------------------------------------------
  # Account Alternate Contacts
  # -----------------------------------------------------------------------------
  - name: sra-account-alternate-contacts-main-ssm
    resource_file: templates/sra-account-alternate-contacts-main-ssm.yaml
    parameter_file: parameters/sra-account-alternate-contacts-main-ssm.json
    deploy_method: stack_set
    deployment_targets:
      accounts:
        - 012345678910

```
However, I am able to successfully deploy the Solution outside of CfCT as a Standalone Solution.

Thanks in Advance

**Comment by andywick-aws** [comment]
Make sure all the parameters within the parameters/sra-account-alternate-contacts-main-ssm.json file are wrapped with quotes. The template in the repo has a bug and will get fixed soon.

Change:
`{
        "ParameterKey": "pComplianceFrequency",
        "ParameterValue": 7
 }`

To:
`{
        "ParameterKey": "pComplianceFrequency",
        "ParameterValue": "7"
    }`

**Comment by AdamDivall** [comment]
Thanks for that.  I've now successfully deployed it via CfCT.
